Changes for Mantis BT 2.0 and Apache 2.4
bueltge/Chosen-for-MantisBT pull request #6
Opened 2017-02-21 14:00 UTC by Hanashi

2017-02-21 14:57 UTC, bueltge requested changes

2017-02-21 14:57 UTC, bueltge commented on chosen/chosen.php
> +			'MantisCore' => '2.0.0',
We should add the older MantisBT version, that other can use the plugin also in older MantsBT version. Can you explain this also for the older version?

2017-02-23 12:49 UTC, Hanashi commented
I changed it and fixed a bug with Mantis 2.0

2017-02-23 12:51 UTC, Hanashi commented on chosen/chosen.php
> +			'MantisCore' => '2.0.0',
Hi, I changed it to '>= 1.2.0, < 3.0', because '1.2.0, 1.3.0, 2.0.0' doesn't work on 1.2 and 1.3.

2017-02-23 13:08 UTC, bueltge approved these changes

2017-02-23 13:08 UTC, merged